export class ProfilePageConstants {
  static readonly attributes = Object.freeze({
    classes: {
      location: 'user-location',
      timezone: 'user-timezone',
      candidateInfo: 'candidate-info',
      candidatePhone: 'candidate-phone',
      candidateEmail: 'candidate-email',
      linkedIn: 'candidate-linkedin',
      candidateResume: 'candidate-resume',
      candidateTimelineDescription: 'timeline-info-details-description',
      timelineDate: 'timeline-info-details-date',
      candidateTimeline: 'candidate-timeline-header',
      newBadge: 'new-badge',
      badgesHeadline: 'badges-headline',
      badgesContainer: 'badges-container-item',
      sectionMenu: 'section-menu',
      noRecord: 'no-record',
      infoHeader: 'information-headline',
      addSectionButton: 'add-section-button',
      sectionMenuItem: 'section-menu-item',
      columnHeader: 'columnheader',
      header: 'headline',
      pipelineName: 'pipeline-name',
      applicationStatus: 'ApplicationStatus',
      redirectText: 'redirect-text',
      otherApplication: 'other-applications',
      stepHeader: 'step__title',
      startAppButton: 'df-button',
      avatar: 'avatar',
    },
  });

  static readonly elementNames = Object.freeze({
    location: 'Location',
    timezone: 'Time Zone',
    candidateInfo: 'Candidate Information',
    candidatePhone: 'Phone number',
    candidateEmail: 'Email',
    linkedIn: 'LinkedIn',
    resume: 'Resume',
    candidateTimeline: 'Candidate Timeline',
    appliedFor: 'Applied for',
    createAccount: 'Created Account on Crossover',
    skillBadge: 'Skills Badges',
    realWorkBadge: 'RealWork Badges',
    introduction: 'Introduction',
    workExperience: 'Work Experience',
    education: 'Education',
    introduceYourself: 'Introduce yourself',
    addWorkExp: 'Add Work Experience',
    addEduction: 'Add Education',
    addSection: 'Add Section',
    award: 'Award',
    certification: 'Certification',
    patent: 'Patent',
    publication: 'Publication',
    sectionMenu: 'Section Menu',
    myApplication: 'My applications',
    myProfile: 'My profile',
    jobApplication: 'Job Applications',
    role: 'Role',
    basicFit: 'Basic Fit',
    requiredSkillBadge: 'Required Skill Badges',
    requiredRealWorkBadges: 'Required Real Work Badges',
    statusNextStep: 'Status / Next Step',
    pipelineName: 'Pipeline Name/ Role Name',
    recommendedJobs: 'Recommended Jobs',
    prodTestPosition: 'Test Position Production Profile',
    stagingTestPosition: 'Test Position Staging Profile',
    basicFitHeader: 'Basic Fit',
    startAssessment: 'Start Assessment',
  });
}
