export class ApplicationPageConstants {
  static readonly attributes = Object.freeze({
    classes: {
      submitApplication: 'apply-button',
      dateError: 'accurate-data-error',
      jobPositionHeader: 'apply-header',
      error: 'error',
      countryCodeDropDown: 'country-name',
      dropDownArrow: 'iti-arrow',
      countryDropdown: 'country-dropdown',
      accurateDataError: 'accurate-data-error',
      profileUserName: 'user-name',
      dialogContainer: 'dialog-container',
      dialogActions: 'dialog-actions',
      tutorialTitle: 'tutorial-title',
      alterTitle: 'dialog-title',
    },
    formcontrolname: {
      firstName: 'firstName',
      lastName: 'lastName',
      email: 'email',
      linkedIn: 'website',
      country: 'country',
      phone: 'phone',
      oneAccount: 'oneAccountConfirmation',
      emailOptIn: 'emailOptIn',
    },
    ids: {
      countrySearchBox: 'country-search-box',
    },
  });

  static readonly elementNames = Object.freeze({
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    linkedIn: 'Linked In',
    country: 'Country',
    phone: 'Phone',
    oneAccount: 'One account confirmation',
    emailOptIn: 'Email opt in',
    submitApplication: 'SUBMIT APPLICATION',
    accurateDataError: 'You must certify that the data you have provided is accurate in order to Apply',
    jobPositionHeader: 'Test Position',
    invalidEmailErrorMsg: 'Invalid email',
    noCountrySelected: '— Please Select —',
    invalidEmail: 'Invalid email',
    countryCodeDropDownArrow: 'Country Code Drop Down',
    countryDropDown: 'Country dropdown',
    countrySearchBox: 'Country Search Box',
    profileHomeUserName: 'Profile home user name',
    takeTour: 'TAKE TOUR',
    next: 'NEXT',
    finish: 'FINISH',
    passwordResetEmailSubject: 'Your account password at',
    takeTourTitle: 'Welcome to your new Crossover Profile!',
    followRecommendation: 'Follow recommendations to fast track your Application',
    followProgress: 'Follow progress of your applications',
    haveApplication: 'You already have an application',
    goToMyApplication: 'Go to my active application',
  });
}
